"""creation tables principales

Revision ID: 86e0f04cf780
Revises: 2b85fd2b88fd
Create Date: 2026-08-21 11:26:53.587236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e0f04cf780'
down_revision: Union[str, Sequence[str], None] = '2b85fd2b88fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_id'), 'produits', ['id'], unique=False)
    op.create_table('annonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('commune', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annonces_id'), 'annonces', ['id'], unique=False)
    op.add_column('utilisateurs', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('utilisateurs', sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False))
    op.add_column('utilisateurs', sa.Column('date_creation', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'utilisateurs', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateurs', type_='unique')
    op.drop_column('utilisateurs', 'date_creation')
    op.drop_column('utilisateurs', 'mot_de_passe_hash')
    op.drop_column('utilisateurs', 'email')
    op.drop_index(op.f('ix_annonces_id'), table_name='annonces')
    op.drop_table('annonces')
    op.drop_index(op.f('ix_produits_id'), table_name='produits')
    op.drop_table('produits')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
