"""ajout tokens reinitialisation mot de passe

Revision ID: 9b8983d30749
Revises: 91cdef44d8a1
Create Date: 2026-09-08 01:08:33.087541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8983d30749'
down_revision: Union[str, Sequence[str], None] = '91cdef44d8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_expiration_used', 'password_reset_tokens', ['expires_at', 'used_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_created_at'), 'password_reset_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_used_at'), 'password_reset_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_utilisateur_id'), 'password_reset_tokens', ['utilisateur_id'], unique=False)
    op.create_index('ix_password_reset_user_expiration', 'password_reset_tokens', ['utilisateur_id', 'expires_at'], unique=False)
    op.create_index('ix_password_reset_user_used', 'password_reset_tokens', ['utilisateur_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_annonces_localisation_source'), 'annonces', ['localisation_source'], unique=False)
    op.create_index(op.f('ix_utilisateurs_date_modification'), 'utilisateurs', ['date_modification'], unique=False)
    op.create_index(op.f('ix_utilisateurs_dernier_login'), 'utilisateurs', ['dernier_login'], unique=False)
    op.create_index(op.f('ix_utilisateurs_email_verifie'), 'utilisateurs', ['email_verifie'], unique=False)
    op.create_index(op.f('ix_utilisateurs_telephone_verifie'), 'utilisateurs', ['telephone_verifie'], unique=False)
    op.create_index('ix_utilisateurs_verification', 'utilisateurs', ['email_verifie', 'telephone_verifie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utilisateurs_verification', table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_telephone_verifie'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email_verifie'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_dernier_login'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_date_modification'), table_name='utilisateurs')
    op.drop_index(op.f('ix_annonces_localisation_source'), table_name='annonces')
    op.drop_index('ix_password_reset_user_used', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_user_expiration', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_utilisateur_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_used_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_created_at'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_expiration_used', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
