"""Ajout des colonnes manquantes

Revision ID: b42c47f9fb74
Revises: cb2c81ec8271
Create Date: 2026-08-29 20:14:21.197995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42c47f9fb74'
down_revision: Union[str, Sequence[str], None] = 'cb2c81ec8271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annonces', 'statut',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('utilisateurs', sa.Column('adresse', sa.String(length=255), nullable=True))
    op.add_column('utilisateurs', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('utilisateurs', 'photo_profil',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('utilisateurs', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('utilisateurs', 'photo_profil',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('utilisateurs', 'description')
    op.drop_column('utilisateurs', 'adresse')
    op.alter_column('annonces', 'statut',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
