"""ajout famille categorie type produit

Revision ID: ba85eff4ae30
Revises: b42c47f9fb74
Create Date: 2026-08-30 20:00:24.559818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba85eff4ae30'
down_revision: Union[str, Sequence[str], None] = 'b42c47f9fb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_familles_id'), 'familles', ['id'], unique=False)
    op.add_column('categories', sa.Column('famille_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_nom_key'), 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'familles', ['famille_id'], ['id'])
    op.add_column('produits', sa.Column('type_produit', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produits', 'type_produit')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_nom_key'), 'categories', ['nom'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'famille_id')
    op.drop_index(op.f('ix_familles_id'), table_name='familles')
    op.drop_table('familles')
    # ### end Alembic commands ###
